name: Release

on:
  workflow_dispatch:
    inputs:
      execute:
        description: Publish crates to crates.io
        required: true
        type: boolean
        default: false

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - run: nix develop --command scripts/release-check.sh
      - if: ${{ !inputs.execute }}
        run: nix develop --command scripts/publish.sh --dry-run
      - if: ${{ inputs.execute }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: nix develop --command scripts/publish.sh --execute
