#[derive(Clone, Copy, Debug)]
/// Embedded VMFB artifact and metadata generated by a graph macro.
pub struct GraphArtifact {
    /// Exported function name inside each VMFB variant.
    pub function_name: &'static str,
    /// Static input metadata, empty when the artifact was imported without a signature.
    pub input_descs: &'static [TensorDesc],
    /// Static output metadata, empty when the artifact was imported without a signature.
    pub output_descs: &'static [TensorDesc],
    /// Backend variants embedded for this graph.
    pub variants: &'static [GraphArtifactVariant],
}

impl GraphArtifact {
    #[cfg(feature = "host-runtime")]
    pub(crate) fn has_typed_signature(&self) -> bool {
        !self.input_descs.is_empty() || !self.output_descs.is_empty()
    }

    /// Returns the first variant compatible with `driver`.
    pub fn variant_for_driver(&self, driver: &str) -> Option<GraphArtifactVariant> {
        self.variants
            .iter()
            .copied()
            .find(|variant| variant.driver == driver)
    }

    /// Returns the first embedded backend variant.
    pub fn first_variant(&self) -> Option<GraphArtifactVariant> {
        self.variants.first().copied()
    }
}

/// Static tensor metadata recorded in a compiled graph artifact.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TensorDesc {
    /// Tensor element type.
    pub elem: DType,
    /// Static tensor shape.
    pub shape: &'static [usize],
}

impl TensorDesc {
    /// Creates tensor metadata from an element type and static shape.
    pub const fn new(elem: DType, shape: &'static [usize]) -> Self {
        Self { elem, shape }
    }
}

/// Element type metadata recorded in a compiled graph artifact.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DType {
    /// Boolean predicate element.
    Bool,
    /// 32-bit IEEE floating-point element.
    F32,
    /// 64-bit IEEE floating-point element.
    F64,
    /// 16-bit IEEE floating-point element.
    F16,
    /// 16-bit brain floating-point element.
    BF16,
    /// Signed 32-bit integer element.
    I32,
    /// Signed 64-bit integer element.
    I64,
}

#[derive(Clone, Copy, Debug)]
/// One compiled backend variant inside a graph artifact.
pub struct GraphArtifactVariant {
    /// IREE VM flatbuffer bytecode.
    pub vmfb: &'static [u8],
    /// IREE target backend used at compile time.
    pub backend: &'static str,
    /// IREE runtime driver required to execute this variant.
    pub driver: &'static str,
    /// Compiler flags used to produce this variant.
    pub compile_flags: &'static [&'static str],
}
