#![cfg_attr(not(feature = "std"), no_std)]
//! Static-shape tensor containers and runtime wrappers for build-time traced
//! IREE VM bytecode artifacts.
//!
//! Graphs are authored from `build.rs` with `knok-build`, which executes traced
//! Rust functions on the compile host and writes generated artifact wrappers to
//! `OUT_DIR`. Target crates import those wrappers with `generated_graphs!`:
//!
//! ```ignore
//! use knok::prelude::*;
//!
//! knok::generated_graphs!(pub mod graphs);
//! ```
//!
//! For repeated hosted inference, construct one [`Engine`] and call generated
//! `graphs::<name>::run(&engine, ...)` wrappers.
//!
//! With default features disabled, `knok` is `no_std + alloc`; hosted runtime
//! execution is unavailable on the target unless the runtime feature set is
//! enabled.

extern crate alloc;

#[cfg(feature = "half")]
pub use half;

pub mod artifact;
/// Backend and runtime driver identifiers supported by generated artifacts.
pub mod backend;
#[doc(hidden)]
pub mod __private {
    pub use crate::private::*;
}
mod private;
pub mod runtime;
/// Fixed-rank tensor containers used by generated graph wrappers.
pub mod tensor;

/// Common imports for target crates that call generated graph wrappers.
pub mod prelude {
    #[cfg(feature = "half")]
    pub use crate::half::{bf16, f16};
    pub use crate::tensor::{
        Tensor0, Tensor1, Tensor2, Tensor3, Tensor4, Tensor5, Tensor6, TensorElement,
    };
    pub use crate::{Backend, Driver};
}

#[macro_export]
/// Includes graph wrapper modules generated by `knok-build` into the target crate.
macro_rules! generated_graphs {
    () => {
        include!(concat!(env!("OUT_DIR"), "/knok_graphs.rs"));
    };
    ($file:literal) => {
        include!(concat!(env!("OUT_DIR"), "/", $file));
    };
    (mod $name:ident) => {
        mod $name {
            include!(concat!(env!("OUT_DIR"), "/knok_graphs.rs"));
        }
    };
    (mod $name:ident, $file:literal) => {
        mod $name {
            include!(concat!(env!("OUT_DIR"), "/", $file));
        }
    };
    (pub mod $name:ident) => {
        pub mod $name {
            include!(concat!(env!("OUT_DIR"), "/knok_graphs.rs"));
        }
    };
    (pub mod $name:ident, $file:literal) => {
        pub mod $name {
            include!(concat!(env!("OUT_DIR"), "/", $file));
        }
    };
}

pub use artifact::{DType, GraphArtifact, GraphArtifactVariant, TensorDesc};
pub use backend::{Backend, Driver, SUPPORTED_BACKENDS};
pub use runtime::{Engine, RuntimeConfig};

/// Result alias used by the public runtime and tensor APIs.
pub type Result<T> = core::result::Result<T, Error>;

/// Errors returned by tensor construction and hosted runtime execution.
#[derive(Debug)]
pub enum Error {
    /// IREE runtime returned an error.
    #[cfg(feature = "host-runtime")]
    Runtime(eerie::runtime::RuntimeError),
    /// Tensor data length does not match the statically declared shape.
    Shape {
        /// Expected static shape.
        expected: &'static [usize],
        /// Runtime shape computed from the input data.
        actual: alloc::vec::Vec<usize>,
    },
    /// Number of runtime inputs did not match artifact metadata.
    InputCountMismatch {
        /// Expected input count.
        expected: usize,
        /// Actual input count.
        actual: usize,
    },
    /// Runtime input dtype did not match artifact metadata.
    InputDTypeMismatch {
        /// Zero-based input index.
        index: usize,
        /// Expected dtype.
        expected: DType,
        /// Actual dtype.
        actual: DType,
    },
    /// Requested backend name is not supported by this crate.
    UnsupportedBackend(&'static str),
    /// No artifact variant matched the requested runtime driver.
    MissingArtifactVariant {
        /// Graph function name.
        function_name: &'static str,
        /// Requested driver name.
        driver: alloc::string::String,
    },
    /// Artifact does not contain any variants.
    MissingDefaultArtifactVariant {
        /// Graph function name.
        function_name: &'static str,
    },
    /// Runtime engine driver does not match a selected artifact variant.
    RuntimeDriverMismatch {
        /// Artifact backend name.
        backend: &'static str,
        /// Driver expected by the artifact variant.
        expected_driver: &'static str,
        /// Driver used by the engine.
        actual_driver: alloc::string::String,
    },
    /// Internal hosted runtime mutex was poisoned.
    EngineLockPoisoned,
    /// A single-output helper was used with a multi-output graph.
    OutputCountMismatch {
        /// Expected output count.
        expected: usize,
        /// Actual output count.
        actual: usize,
    },
    /// Requested output index is outside the graph output list.
    OutputIndexOutOfBounds {
        /// Requested output index.
        index: usize,
        /// Number of available outputs.
        len: usize,
    },
    /// Hosted runtime APIs were called without the hosted runtime feature.
    HostedRuntimeDisabled,
}

#[cfg(feature = "host-runtime")]
impl From<eerie::runtime::RuntimeError> for Error {
    fn from(error: eerie::runtime::RuntimeError) -> Self {
        Self::Runtime(error)
    }
}

impl core::fmt::Display for Error {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            #[cfg(feature = "host-runtime")]
            Self::Runtime(error) => write!(formatter, "runtime error: {error}"),
            Self::Shape { expected, actual } => {
                write!(
                    formatter,
                    "tensor shape mismatch: expected {expected:?}, got {actual:?}"
                )
            }
            Self::InputCountMismatch { expected, actual } => {
                write!(
                    formatter,
                    "runtime input count mismatch: expected {expected}, got {actual}"
                )
            }
            Self::InputDTypeMismatch {
                index,
                expected,
                actual,
            } => {
                write!(
                    formatter,
                    "runtime input {index} dtype mismatch: expected {expected:?}, got {actual:?}"
                )
            }
            Self::UnsupportedBackend(backend) => {
                write!(formatter, "unsupported backend: {backend}")
            }
            Self::MissingArtifactVariant {
                function_name,
                driver,
            } => {
                write!(
                    formatter,
                    "no artifact variant for function {function_name} and runtime driver {driver}"
                )
            }
            Self::MissingDefaultArtifactVariant { function_name } => {
                write!(
                    formatter,
                    "artifact for function {function_name} has no compiled variants"
                )
            }
            Self::RuntimeDriverMismatch {
                backend,
                expected_driver,
                actual_driver,
            } => {
                write!(
                    formatter,
                    "runtime driver mismatch for backend {backend}: expected {expected_driver}, got {actual_driver}"
                )
            }
            Self::EngineLockPoisoned => formatter.write_str("runtime engine cache lock poisoned"),
            Self::OutputCountMismatch { expected, actual } => {
                write!(
                    formatter,
                    "runtime output count mismatch: expected {expected}, got {actual}"
                )
            }
            Self::OutputIndexOutOfBounds { index, len } => {
                write!(
                    formatter,
                    "runtime output index out of bounds: index {index}, len {len}"
                )
            }
            Self::HostedRuntimeDisabled => formatter.write_str("host runtime feature is disabled"),
        }
    }
}

impl core::error::Error for Error {}
